//! Execution Engine Type Definitions

use crate::agentic::core::Message;
use crate::agentic::tools::pipeline::SubagentParentInfo;
use std::collections::HashMap;
use tokio_util::sync::CancellationToken;

/// Execution context
#[derive(Debug, Clone)]
pub struct ExecutionContext {
    pub session_id: String,
    pub dialog_turn_id: String,
    pub turn_index: usize,
    pub agent_type: String,
    pub context: HashMap<String, String>,
    pub subagent_parent_info: Option<SubagentParentInfo>,
    pub skip_tool_confirmation: bool,
}

/// Round context
#[derive(Debug, Clone)]
pub struct RoundContext {
    pub session_id: String,
    pub subagent_parent_info: Option<SubagentParentInfo>,
    pub dialog_turn_id: String,
    pub turn_index: usize,
    pub round_number: usize,
    pub messages: Vec<Message>,
    pub available_tools: Vec<String>,
    pub model_name: String,
    pub agent_type: String,
    pub context_vars: HashMap<String, String>,
    pub cancellation_token: CancellationToken,
}

/// Round result
#[derive(Debug, Clone)]
pub struct RoundResult {
    pub assistant_message: Message,
    pub tool_calls: Vec<crate::agentic::core::ToolCall>,
    pub tool_result_messages: Vec<Message>,
    pub has_more_rounds: bool,
    pub finish_reason: FinishReason,
    /// Token usage statistics (from model response)
    pub usage: Option<crate::util::types::ai::GeminiUsage>,
}

/// Finish reason
#[derive(Debug, Clone, PartialEq)]
pub enum FinishReason {
    /// Normal completion
    Complete,
    /// Need to execute tools
    ToolCalls,
    /// Reached maximum rounds
    MaxRounds,
    /// User cancelled
    Cancelled,
    /// Error
    Error,
}

/// Execution result
#[derive(Debug, Clone)]
pub struct ExecutionResult {
    /// Last assistant message
    pub final_message: Message,
    pub total_rounds: usize,
    pub success: bool,
    /// All new messages generated by this execution (including AI responses and tool results)
    pub new_messages: Vec<Message>,
}
