//! Execution Engine Type Definitions

use crate::agentic::core::Message;
use crate::agentic::round_preempt::DialogRoundPreemptSource;
use crate::agentic::tools::pipeline::SubagentParentInfo;
use crate::agentic::workspace::WorkspaceServices;
use crate::agentic::WorkspaceBinding;
use serde_json::Value;
use std::collections::HashMap;
use std::sync::Arc;
use tokio_util::sync::CancellationToken;

/// Execution context
#[derive(Clone)]
pub struct ExecutionContext {
    pub session_id: String,
    pub dialog_turn_id: String,
    pub turn_index: usize,
    pub agent_type: String,
    pub workspace: Option<WorkspaceBinding>,
    pub context: HashMap<String, String>,
    pub subagent_parent_info: Option<SubagentParentInfo>,
    pub skip_tool_confirmation: bool,
    /// Workspace I/O services (filesystem + shell) injected into tools
    pub workspace_services: Option<WorkspaceServices>,
    /// When set, engine may end the turn after a full model round if a user message was queued.
    pub round_preempt: Option<Arc<dyn DialogRoundPreemptSource>>,
}

/// Round context
#[derive(Debug, Clone)]
pub struct RoundContext {
    pub session_id: String,
    pub subagent_parent_info: Option<SubagentParentInfo>,
    pub dialog_turn_id: String,
    pub turn_index: usize,
    pub round_number: usize,
    pub workspace: Option<WorkspaceBinding>,
    pub messages: Vec<Message>,
    pub available_tools: Vec<String>,
    pub model_name: String,
    pub agent_type: String,
    pub context_vars: HashMap<String, String>,
    pub cancellation_token: CancellationToken,
    pub workspace_services: Option<WorkspaceServices>,
}

/// Round result
#[derive(Debug, Clone)]
pub struct RoundResult {
    pub assistant_message: Message,
    pub tool_calls: Vec<crate::agentic::core::ToolCall>,
    pub tool_result_messages: Vec<Message>,
    pub has_more_rounds: bool,
    pub finish_reason: FinishReason,
    /// Token usage statistics (from model response)
    pub usage: Option<crate::util::types::ai::GeminiUsage>,
    /// Provider-specific metadata returned by the model.
    pub provider_metadata: Option<Value>,
}

/// Finish reason
#[derive(Debug, Clone, PartialEq)]
pub enum FinishReason {
    /// Normal completion
    Complete,
    /// Need to execute tools
    ToolCalls,
    /// Reached maximum rounds
    MaxRounds,
    /// User cancelled
    Cancelled,
    /// Error
    Error,
}

/// Execution result
#[derive(Debug, Clone)]
pub struct ExecutionResult {
    /// Last assistant message
    pub final_message: Message,
    pub total_rounds: usize,
    pub success: bool,
    /// All new messages generated by this execution (including AI responses and tool results)
    pub new_messages: Vec<Message>,
}
