//! Conversation coordinator
//!
//! Top-level component that integrates all subsystems and provides a unified interface

use super::{scheduler::DialogSubmissionPolicy, turn_outcome::TurnOutcome};
use crate::agentic::agents::get_agent_registry;
use crate::agentic::core::{
    has_prompt_markup, Message, MessageContent, ProcessingPhase, PromptEnvelope, Session,
    SessionConfig, SessionState, SessionSummary, TurnStats,
};
use crate::agentic::events::{
    AgenticEvent, EventPriority, EventQueue, EventRouter, EventSubscriber,
};
use crate::agentic::execution::{ExecutionContext, ExecutionEngine};
use crate::agentic::image_analysis::ImageContextData;
use crate::agentic::session::SessionManager;
use crate::agentic::tools::pipeline::{SubagentParentInfo, ToolPipeline};
use crate::agentic::WorkspaceBinding;
use crate::service::bootstrap::is_workspace_bootstrap_pending;
use crate::util::errors::{BitFunError, BitFunResult};
use log::{debug, error, info, warn};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::OnceLock;
use tokio::sync::mpsc;
use tokio_util::sync::CancellationToken;

/// Subagent execution result
///
/// Contains the text response after subagent execution
#[derive(Debug, Clone)]
pub struct SubagentResult {
    /// AI text response
    pub text: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DialogTriggerSource {
    DesktopUi,
    DesktopApi,
    AgentSession,
    RemoteRelay,
    Bot,
    Cli,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AssistantBootstrapSkipReason {
    BootstrapNotRequired,
    SessionHasExistingTurns,
    SessionNotIdle,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AssistantBootstrapBlockReason {
    ModelUnavailable,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AssistantBootstrapEnsureOutcome {
    Started {
        session_id: String,
        turn_id: String,
    },
    Skipped {
        session_id: String,
        reason: AssistantBootstrapSkipReason,
    },
    Blocked {
        session_id: String,
        reason: AssistantBootstrapBlockReason,
        detail: String,
    },
}

const ASSISTANT_BOOTSTRAP_AGENT_TYPE: &str = "Claw";

/// Cancel token cleanup guard
///
/// Automatically cleans up cancel tokens in ExecutionEngine when dropped
struct CancelTokenGuard {
    execution_engine: Arc<ExecutionEngine>,
    dialog_turn_id: String,
}

impl Drop for CancelTokenGuard {
    fn drop(&mut self) {
        let execution_engine = self.execution_engine.clone();
        let dialog_turn_id = self.dialog_turn_id.clone();

        tokio::spawn(async move {
            execution_engine.cleanup_cancel_token(&dialog_turn_id).await;
        });
    }
}

/// Conversation coordinator
pub struct ConversationCoordinator {
    session_manager: Arc<SessionManager>,
    execution_engine: Arc<ExecutionEngine>,
    tool_pipeline: Arc<ToolPipeline>,
    event_queue: Arc<EventQueue>,
    event_router: Arc<EventRouter>,
    /// Notifies DialogScheduler of turn outcomes; injected after construction
    scheduler_notify_tx: OnceLock<mpsc::Sender<(String, TurnOutcome)>>,
}

impl ConversationCoordinator {
    fn session_workspace_binding(session: &Session) -> Option<WorkspaceBinding> {
        Self::config_workspace_binding(&session.config)
    }

    fn config_workspace_binding(config: &SessionConfig) -> Option<WorkspaceBinding> {
        config
            .workspace_path
            .as_ref()
            .map(|workspace_path| WorkspaceBinding::new(None, PathBuf::from(workspace_path)))
    }

    fn normalize_agent_type(agent_type: &str) -> String {
        if agent_type.trim().is_empty() {
            "agentic".to_string()
        } else {
            agent_type.trim().to_string()
        }
    }

    fn ensure_user_message_metadata_object(
        metadata: Option<serde_json::Value>,
    ) -> serde_json::Value {
        match metadata {
            Some(value) if value.is_object() => value,
            Some(value) => serde_json::json!({ "raw_metadata": value }),
            None => serde_json::json!({}),
        }
    }

    fn assistant_bootstrap_kickoff_query(is_chinese: bool) -> &'static str {
        if is_chinese {
            "请开始初始化"
        } else {
            "Please start bootstrap"
        }
    }

    fn assistant_bootstrap_system_reminder(kickoff_query: &str, expected_reply_language: &str) -> String {
        format!(
            "This is an automatic bootstrap kickoff generated by the system because this assistant workspace still contains BOOTSTRAP.md. \
Treat the user message `{kickoff_query}` only as a start signal, begin bootstrap immediately, and finish it in this session. \
Use {expected_reply_language} for all user-facing replies during bootstrap unless the user later asks to switch languages. \
Update the persona files and delete BOOTSTRAP.md as soon as bootstrap is complete."
        )
    }

    pub fn new(
        session_manager: Arc<SessionManager>,
        execution_engine: Arc<ExecutionEngine>,
        tool_pipeline: Arc<ToolPipeline>,
        event_queue: Arc<EventQueue>,
        event_router: Arc<EventRouter>,
    ) -> Self {
        Self {
            session_manager,
            execution_engine,
            tool_pipeline,
            event_queue,
            event_router,
            scheduler_notify_tx: OnceLock::new(),
        }
    }

    /// Inject the DialogScheduler notification channel after construction.
    /// Called once during app initialization after the scheduler is created.
    pub fn set_scheduler_notifier(&self, tx: mpsc::Sender<(String, TurnOutcome)>) {
        let _ = self.scheduler_notify_tx.set(tx);
    }

    /// Create a new session
    pub async fn create_session(
        &self,
        session_name: String,
        agent_type: String,
        config: SessionConfig,
    ) -> BitFunResult<Session> {
        let workspace_path = config.workspace_path.clone().ok_or_else(|| {
            BitFunError::Validation(
                "workspace_path is required when creating a session".to_string(),
            )
        })?;
        self.create_session_with_workspace_and_creator(
            None,
            session_name,
            agent_type,
            config,
            workspace_path,
            None,
        )
        .await
    }

    /// Create a new session with optional session ID
    pub async fn create_session_with_id(
        &self,
        session_id: Option<String>,
        session_name: String,
        agent_type: String,
        config: SessionConfig,
    ) -> BitFunResult<Session> {
        let workspace_path = config.workspace_path.clone().ok_or_else(|| {
            BitFunError::Validation(
                "workspace_path is required when creating a session".to_string(),
            )
        })?;
        self.create_session_with_workspace_and_creator(
            session_id,
            session_name,
            agent_type,
            config,
            workspace_path,
            None,
        )
        .await
    }

    /// Create a new session with optional session ID and workspace binding.
    /// `workspace_path` is forwarded in the `SessionCreated` event and also stored
    /// in the session's in-memory config so it can be retrieved without disk access.
    pub async fn create_session_with_workspace(
        &self,
        session_id: Option<String>,
        session_name: String,
        agent_type: String,
        config: SessionConfig,
        workspace_path: String,
    ) -> BitFunResult<Session> {
        self.create_session_with_workspace_and_creator(
            session_id,
            session_name,
            agent_type,
            config,
            workspace_path,
            None,
        )
        .await
    }

    /// Create a new session with explicit creator identity.
    pub async fn create_session_with_workspace_and_creator(
        &self,
        session_id: Option<String>,
        session_name: String,
        agent_type: String,
        mut config: SessionConfig,
        workspace_path: String,
        created_by: Option<String>,
    ) -> BitFunResult<Session> {
        // Persist the workspace binding inside the session config so execution can
        // consistently restore the correct workspace regardless of the entry point.
        config.workspace_path = Some(workspace_path.clone());
        let agent_type = Self::normalize_agent_type(&agent_type);
        let session = self
            .session_manager
            .create_session_with_id_and_creator(
                session_id,
                session_name,
                agent_type,
                config,
                created_by,
            )
            .await?;

        self.sync_session_metadata_to_workspace(&session, workspace_path.clone())
            .await;

        self.emit_event(AgenticEvent::SessionCreated {
            session_id: session.session_id.clone(),
            session_name: session.session_name.clone(),
            agent_type: session.agent_type.clone(),
            workspace_path: Some(workspace_path),
        })
        .await;
        Ok(session)
    }

    async fn sync_session_metadata_to_workspace(&self, session: &Session, workspace_path: String) {
        use crate::agentic::persistence::PersistenceManager;
        use crate::infrastructure::PathManager;
        use crate::service::session::{SessionMetadata, SessionStatus};

        let path_manager = match PathManager::new() {
            Ok(pm) => Arc::new(pm),
            Err(e) => {
                warn!("Failed to initialize PathManager for session metadata sync: {e}");
                return;
            }
        };

        let workspace_path_buf = std::path::PathBuf::from(&workspace_path);
        let persistence_manager = match PersistenceManager::new(path_manager) {
            Ok(manager) => manager,
            Err(e) => {
                warn!("Failed to initialize PersistenceManager for session metadata sync: {e}");
                return;
            }
        };

        let now_ms = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        let existing = match persistence_manager
            .load_session_metadata(&workspace_path_buf, &session.session_id)
            .await
        {
            Ok(meta) => meta,
            Err(e) => {
                debug!(
                    "Failed to load existing session metadata before sync: session_id={}, error={}",
                    session.session_id, e
                );
                None
            }
        };

        let metadata = SessionMetadata {
            session_id: session.session_id.clone(),
            session_name: session.session_name.clone(),
            agent_type: session.agent_type.clone(),
            created_by: session
                .created_by
                .clone()
                .or_else(|| existing.as_ref().and_then(|m| m.created_by.clone())),
            model_name: existing
                .as_ref()
                .map(|m| m.model_name.clone())
                .filter(|name| !name.is_empty())
                .unwrap_or_else(|| "default".to_string()),
            created_at: existing.as_ref().map(|m| m.created_at).unwrap_or(now_ms),
            last_active_at: now_ms,
            turn_count: existing.as_ref().map(|m| m.turn_count).unwrap_or(0),
            message_count: existing.as_ref().map(|m| m.message_count).unwrap_or(0),
            tool_call_count: existing.as_ref().map(|m| m.tool_call_count).unwrap_or(0),
            status: existing
                .as_ref()
                .map(|m| m.status.clone())
                .unwrap_or(SessionStatus::Active),
            terminal_session_id: existing
                .as_ref()
                .and_then(|m| m.terminal_session_id.clone()),
            snapshot_session_id: session.snapshot_session_id.clone().or_else(|| {
                existing
                    .as_ref()
                    .and_then(|m| m.snapshot_session_id.clone())
            }),
            tags: existing
                .as_ref()
                .map(|m| m.tags.clone())
                .unwrap_or_default(),
            custom_metadata: existing.as_ref().and_then(|m| m.custom_metadata.clone()),
            todos: existing.as_ref().and_then(|m| m.todos.clone()),
            workspace_path: Some(workspace_path),
        };

        if let Err(e) = persistence_manager
            .save_session_metadata(&workspace_path_buf, &metadata)
            .await
        {
            warn!(
                "Failed to sync session metadata to workspace: session_id={}, error={}",
                session.session_id, e
            );
        }
    }

    /// Ensure the completed/failed/cancelled turn is persisted to the workspace
    /// session storage. If the frontend already saved a richer version
    /// during streaming, we only update the final status; otherwise we create
    /// a minimal record with the user message so the turn is never lost.
    /// Safety-net persistence: only creates a minimal record when the frontend
    /// has not saved anything yet.  The frontend's PersistenceModule is the
    /// authoritative writer for turn content (model rounds, text, tools, etc.)
    /// and final status.  This function must NOT overwrite frontend-managed
    /// data, because the spawned task always runs before the frontend receives
    /// the DialogTurnCompleted event via the transport layer, and the existing
    /// disk data from debounced saves may have incomplete model rounds.
    async fn finalize_turn_in_workspace(
        session_id: &str,
        turn_id: &str,
        turn_index: usize,
        user_input: &str,
        workspace_path: &str,
        status: crate::service::session::TurnStatus,
        user_message_metadata: Option<serde_json::Value>,
    ) {
        use crate::agentic::persistence::PersistenceManager;
        use crate::infrastructure::PathManager;
        use crate::service::session::{DialogTurnData, UserMessageData};

        let path_manager = match PathManager::new() {
            Ok(pm) => std::sync::Arc::new(pm),
            Err(_) => return,
        };

        let workspace_path_buf = std::path::PathBuf::from(workspace_path);
        let persistence_manager = match PersistenceManager::new(path_manager) {
            Ok(manager) => manager,
            Err(_) => return,
        };

        if let Ok(Some(_existing)) = persistence_manager
            .load_dialog_turn(&workspace_path_buf, session_id, turn_index)
            .await
        {
            return;
        }

        let now_ms = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        let mut turn_data = DialogTurnData::new(
            turn_id.to_string(),
            turn_index,
            session_id.to_string(),
            UserMessageData {
                id: format!("{}-user", turn_id),
                content: user_input.to_string(),
                timestamp: now_ms,
                metadata: user_message_metadata,
            },
        );
        turn_data.status = status;
        turn_data.end_time = Some(now_ms);
        turn_data.duration_ms = Some(now_ms.saturating_sub(turn_data.start_time));

        if let Err(e) = persistence_manager
            .save_dialog_turn(&workspace_path_buf, &turn_data)
            .await
        {
            warn!(
                "Failed to finalize turn in workspace: session_id={}, turn_index={}, error={}",
                session_id, turn_index, e
            );
        }
    }

    /// Create a subagent session for internal AI execution.
    /// Unlike `create_session`, this does NOT emit `SessionCreated` to the transport layer,
    /// because subagent sessions are internal implementation details of the execution engine
    /// and must never appear as top-level items in the UI.
    async fn create_subagent_session(
        &self,
        session_name: String,
        agent_type: String,
        config: SessionConfig,
        creator_session_id: Option<&str>,
    ) -> BitFunResult<Session> {
        self.session_manager
            .create_session_with_id_and_creator(
                None,
                session_name,
                agent_type,
                config,
                creator_session_id.map(|session_id| format!("session-{}", session_id)),
            )
            .await
    }

    async fn wrap_user_input(
        &self,
        agent_type: &str,
        user_input: String,
        workspace: Option<&WorkspaceBinding>,
    ) -> BitFunResult<String> {
        let agent_registry = get_agent_registry();
        if let Some(workspace) = workspace {
            agent_registry
                .load_custom_subagents(workspace.root_path())
                .await;
        }
        let current_agent = agent_registry
            .get_agent(agent_type, workspace.map(|binding| binding.root_path()))
            .ok_or_else(|| BitFunError::NotFound(format!("Agent not found: {}", agent_type)))?;
        let system_reminder = current_agent.get_system_reminder(0).await?;

        let mut wrapped_user_input = if has_prompt_markup(&user_input) {
            user_input
        } else {
            let mut envelope = PromptEnvelope::new();
            envelope.push_user_query(user_input);
            envelope.render()
        };
        if !system_reminder.is_empty() {
            let mut envelope = PromptEnvelope::new();
            envelope.push_system_reminder(system_reminder);
            if !wrapped_user_input.is_empty() {
                wrapped_user_input.push('\n');
            }
            wrapped_user_input.push_str(&envelope.render());
        }
        Ok(wrapped_user_input)
    }

    pub async fn ensure_assistant_bootstrap(
        &self,
        session_id: String,
        workspace_path: String,
    ) -> BitFunResult<AssistantBootstrapEnsureOutcome> {
        let workspace_root = PathBuf::from(&workspace_path);
        if !is_workspace_bootstrap_pending(&workspace_root) {
            return Ok(AssistantBootstrapEnsureOutcome::Skipped {
                session_id,
                reason: AssistantBootstrapSkipReason::BootstrapNotRequired,
            });
        }

        let session = match self.session_manager.get_session(&session_id) {
            Some(session) => session,
            None => {
                self.session_manager
                    .restore_session(&workspace_root, &session_id)
                    .await?
            }
        };

        if self.session_manager.get_turn_count(&session_id) > 0 {
            return Ok(AssistantBootstrapEnsureOutcome::Skipped {
                session_id,
                reason: AssistantBootstrapSkipReason::SessionHasExistingTurns,
            });
        }

        if !matches!(session.state, SessionState::Idle) {
            return Ok(AssistantBootstrapEnsureOutcome::Skipped {
                session_id,
                reason: AssistantBootstrapSkipReason::SessionNotIdle,
            });
        }

        let is_chinese = Self::is_chinese_locale().await;
        let kickoff_query = Self::assistant_bootstrap_kickoff_query(is_chinese);
        let expected_reply_language = if is_chinese { "Chinese" } else { "English" };
        let workspace_binding = WorkspaceBinding::new(None, workspace_root.clone());
        let model_id = self
            .execution_engine
            .resolve_model_id_for_turn(
                &session,
                ASSISTANT_BOOTSTRAP_AGENT_TYPE,
                Some(&workspace_binding),
                kickoff_query,
                0,
            )
            .await?;

        let ai_client_factory =
            match crate::infrastructure::ai::get_global_ai_client_factory().await {
                Ok(factory) => factory,
                Err(error) => {
                    return Ok(AssistantBootstrapEnsureOutcome::Blocked {
                        session_id,
                        reason: AssistantBootstrapBlockReason::ModelUnavailable,
                        detail: format!("Failed to get AI client factory: {error}"),
                    });
                }
            };

        if let Err(error) = ai_client_factory.get_client_resolved(&model_id).await {
            return Ok(AssistantBootstrapEnsureOutcome::Blocked {
                session_id,
                reason: AssistantBootstrapBlockReason::ModelUnavailable,
                detail: format!("Failed to get AI client (model_id={model_id}): {error}"),
            });
        }

        let mut envelope = PromptEnvelope::new();
        envelope.push_system_reminder(Self::assistant_bootstrap_system_reminder(
            kickoff_query,
            expected_reply_language,
        ));
        envelope.push_user_query(kickoff_query.to_string());

        let turn_id = format!("assistant-bootstrap-{}", uuid::Uuid::new_v4());
        let metadata = serde_json::json!({
            "assistant_bootstrap": {
                "trigger": "lazy_auto",
                "system_generated": true,
                "workspace_path": workspace_path,
            }
        });

        self.start_dialog_turn_internal(
            session_id.clone(),
            envelope.render(),
            Some(kickoff_query.to_string()),
            None,
            Some(turn_id.clone()),
            ASSISTANT_BOOTSTRAP_AGENT_TYPE.to_string(),
            Some(workspace_root.to_string_lossy().to_string()),
            DialogSubmissionPolicy::for_source(DialogTriggerSource::DesktopApi)
                .with_skip_tool_confirmation(true),
            Some(metadata),
            true,
        )
        .await?;

        Ok(AssistantBootstrapEnsureOutcome::Started {
            session_id,
            turn_id,
        })
    }

    /// Start a new dialog turn
    /// Note: Events are sent to frontend via EventLoop, no Stream returned.
    /// Submission behavior is controlled by `submission_policy`, which provides
    /// default per-source behavior while still allowing selective overrides.
    pub async fn start_dialog_turn(
        &self,
        session_id: String,
        user_input: String,
        original_user_input: Option<String>,
        turn_id: Option<String>,
        agent_type: String,
        workspace_path: Option<String>,
        submission_policy: DialogSubmissionPolicy,
    ) -> BitFunResult<()> {
        self.start_dialog_turn_internal(
            session_id,
            user_input,
            original_user_input,
            None,
            turn_id,
            agent_type,
            workspace_path,
            submission_policy,
            None,
            false,
        )
        .await
    }

    pub async fn start_dialog_turn_with_image_contexts(
        &self,
        session_id: String,
        user_input: String,
        original_user_input: Option<String>,
        image_contexts: Vec<ImageContextData>,
        turn_id: Option<String>,
        agent_type: String,
        workspace_path: Option<String>,
        submission_policy: DialogSubmissionPolicy,
    ) -> BitFunResult<()> {
        self.start_dialog_turn_internal(
            session_id,
            user_input,
            original_user_input,
            Some(image_contexts),
            turn_id,
            agent_type,
            workspace_path,
            submission_policy,
            None,
            false,
        )
        .await
    }

    /// Pre-analyze images using the configured vision model.
    ///
    /// Strategy:
    /// 1. Vision model configured → analyze images → enhance user message with text descriptions → clear image_contexts
    /// 2. No vision model → reject with a user-friendly message
    async fn pre_analyze_images_if_needed(
        &self,
        user_input: String,
        image_contexts: Option<Vec<ImageContextData>>,
        session_id: &str,
        image_metadata: Option<serde_json::Value>,
        workspace: Option<WorkspaceBinding>,
    ) -> BitFunResult<(String, Option<Vec<ImageContextData>>)> {
        let images = match &image_contexts {
            Some(imgs) if !imgs.is_empty() => imgs,
            _ => return Ok((user_input, image_contexts)),
        };

        use crate::agentic::image_analysis::{
            resolve_vision_model_from_global_config, AnalyzeImagesRequest, ImageAnalyzer,
            MessageEnhancer,
        };
        use crate::infrastructure::ai::get_global_ai_client_factory;

        let vision_model = match resolve_vision_model_from_global_config().await {
            Ok(m) => m,
            Err(_e) => {
                let is_chinese = Self::is_chinese_locale().await;
                let msg = if is_chinese {
                    "请先在桌面端「设置 → AI 模型」中配置图片理解模型，然后再发送图片。"
                } else {
                    "Please configure an Image Understanding Model in Settings → AI Models on the desktop app before sending images."
                };
                return Err(BitFunError::service(msg));
            }
        };

        let factory = match get_global_ai_client_factory().await {
            Ok(f) => f,
            Err(e) => {
                warn!("Failed to get AI client factory for vision: {}", e);
                return Ok((user_input, image_contexts));
            }
        };

        let vision_client = match factory.get_client_by_id(&vision_model.id).await {
            Ok(c) => c,
            Err(e) => {
                warn!("Failed to create vision AI client: {}", e);
                return Ok((user_input, image_contexts));
            }
        };

        let workspace_path = workspace.map(|binding| binding.root_path);
        let request_workspace_path = workspace_path
            .as_ref()
            .map(|path| path.to_string_lossy().to_string());
        let analyzer = ImageAnalyzer::new(workspace_path, vision_client);
        let request = AnalyzeImagesRequest {
            images: images.clone(),
            user_message: Some(user_input.clone()),
            session_id: session_id.to_string(),
            workspace_path: request_workspace_path,
        };

        self.emit_event(AgenticEvent::ImageAnalysisStarted {
            session_id: session_id.to_string(),
            image_count: images.len(),
            user_input: user_input.clone(),
            image_metadata: image_metadata.clone(),
        })
        .await;

        let analysis_start = std::time::Instant::now();

        match analyzer.analyze_images(request, &vision_model).await {
            Ok(results) => {
                let duration_ms = analysis_start.elapsed().as_millis() as u64;

                self.emit_event(AgenticEvent::ImageAnalysisCompleted {
                    session_id: session_id.to_string(),
                    success: true,
                    duration_ms,
                })
                .await;

                info!(
                    "Vision pre-analysis completed: session={}, images={}, results={}, duration={}ms",
                    session_id,
                    images.len(),
                    results.len(),
                    duration_ms
                );
                let enhanced =
                    MessageEnhancer::enhance_with_image_analysis(&user_input, &results, &[]);
                Ok((enhanced, None))
            }
            Err(e) => {
                let duration_ms = analysis_start.elapsed().as_millis() as u64;

                self.emit_event(AgenticEvent::ImageAnalysisCompleted {
                    session_id: session_id.to_string(),
                    success: false,
                    duration_ms,
                })
                .await;

                warn!(
                    "Vision pre-analysis failed, falling back to multimodal: session={}, error={}",
                    session_id, e
                );
                Ok((user_input, image_contexts))
            }
        }
    }

    async fn is_chinese_locale() -> bool {
        use crate::service::config::get_global_config_service;
        use crate::service::config::types::AppConfig;
        let Ok(config_service) = get_global_config_service().await else {
            return true;
        };
        let app: AppConfig = config_service
            .get_config(Some("app"))
            .await
            .unwrap_or_default();
        app.language.starts_with("zh")
    }

    async fn start_dialog_turn_internal(
        &self,
        session_id: String,
        user_input: String,
        original_user_input: Option<String>,
        image_contexts: Option<Vec<ImageContextData>>,
        turn_id: Option<String>,
        agent_type: String,
        workspace_path: Option<String>,
        submission_policy: DialogSubmissionPolicy,
        extra_user_message_metadata: Option<serde_json::Value>,
        suppress_session_title_generation: bool,
    ) -> BitFunResult<()> {
        // Get latest session, restoring from persistence on demand so every entry
        // point can use the same start_dialog_turn flow.
        let session = match self.session_manager.get_session(&session_id) {
            Some(session) => session,
            None => {
                debug!(
                    "Session not found in memory, attempting restore before starting dialog: session_id={}",
                    session_id
                );
                let workspace_path = workspace_path.clone().ok_or_else(|| {
                    BitFunError::Validation(format!(
                        "workspace_path is required when restoring session: {}",
                        session_id
                    ))
                })?;
                self.session_manager
                    .restore_session(Path::new(&workspace_path), &session_id)
                    .await?
            }
        };

        let requested_agent_type = agent_type.trim().to_string();
        let provisional_agent_type = if !requested_agent_type.is_empty() {
            requested_agent_type.clone()
        } else if !session.agent_type.is_empty() {
            session.agent_type.clone()
        } else {
            "agentic".to_string()
        };
        let effective_agent_type = Self::normalize_agent_type(&provisional_agent_type);

        debug!(
            "Resolved dialog turn agent type: session_id={}, turn_id={}, requested_agent_type={}, session_agent_type={}, effective_agent_type={}, trigger_source={:?}, queue_priority={:?}, skip_tool_confirmation={}",
            session_id,
            turn_id.as_deref().unwrap_or(""),
            if requested_agent_type.is_empty() {
                "<empty>"
            } else {
                requested_agent_type.as_str()
            },
            if session.agent_type.is_empty() {
                "<empty>"
            } else {
                session.agent_type.as_str()
            },
            effective_agent_type,
            submission_policy.trigger_source,
            submission_policy.queue_priority,
            submission_policy.skip_tool_confirmation
        );

        if session.agent_type != effective_agent_type {
            self.session_manager
                .update_session_agent_type(&session_id, &effective_agent_type)
                .await?;
        }

        debug!(
            "Checking session state: session_id={}, state={:?}",
            session_id, session.state
        );

        // Check session state
        // Allow Idle or any error state (user can retry after error)
        // If Processing, cancel request hasn't arrived yet, reject new dialog
        match &session.state {
            SessionState::Idle => {
                debug!(
                    "Session state is Idle, allowing new dialog: session_id={}",
                    session_id
                );
            }
            SessionState::Error { .. } => {
                debug!(
                    "Session in error state, allowing new dialog (user retry): session_id={}",
                    session_id
                );
            }
            SessionState::Processing {
                current_turn_id,
                phase,
            } => {
                warn!(
                    "Session still processing, rejecting new dialog: session_id={}, current_turn_id={}, phase={:?}",
                    session_id,
                    current_turn_id,
                    phase
                );
                return Err(BitFunError::Validation(format!(
                    "Session state does not allow starting new dialog: {:?}",
                    session.state
                )));
            }
        }

        // Ensure session history is loaded into memory
        // Critical fix: prevent unloaded history after app restart
        let context_messages = self
            .session_manager
            .get_context_messages(&session_id)
            .await?;

        // Check if restore is needed:
        // - Empty context needs restore
        // - Only 1 message (likely just system prompt) with existing turns needs restore
        // - Sessions with multiple turns should have > 1 messages (at least system + user + assistant)
        let needs_restore = if context_messages.is_empty() {
            debug!(
                "Session {} context is empty, restoring from persistence",
                session_id
            );
            true
        } else if context_messages.len() == 1 && session.dialog_turn_ids.len() > 0 {
            debug!(
                "Session {} has {} turns but only {} messages, restoring history",
                session_id,
                session.dialog_turn_ids.len(),
                context_messages.len()
            );
            true
        } else {
            debug!(
                "Session {} context exists ({} messages, {} turns), no restore needed",
                session_id,
                context_messages.len(),
                session.dialog_turn_ids.len()
            );
            false
        };

        if needs_restore {
            debug!(
                "Starting session history restore: session_id={}",
                session_id
            );
            match self
                .session_manager
                .restore_session(
                    Path::new(
                        session
                            .config
                            .workspace_path
                            .as_deref()
                            .or(workspace_path.as_deref())
                            .ok_or_else(|| {
                                BitFunError::Validation(format!(
                                    "workspace_path is required when restoring session: {}",
                                    session_id
                                ))
                            })?,
                    ),
                    &session_id,
                )
                .await
            {
                Ok(_) => {
                    let restored_messages = self
                        .session_manager
                        .get_context_messages(&session_id)
                        .await?;
                    info!(
                        "Session history restored from persistence: session_id={}, messages: {} -> {}",
                        session_id,
                        context_messages.len(),
                        restored_messages.len()
                    );
                }
                Err(e) => {
                    debug!(
                        "Failed to restore session history (may be new session): session_id={}, error={}",
                        session_id,
                        e
                    );
                }
            }
        }

        let original_user_input = original_user_input.unwrap_or_else(|| user_input.clone());

        let mut user_message_metadata = extra_user_message_metadata;

        // Build image metadata for workspace turn persistence (before image_contexts is consumed)
        // Also stores original_text so the UI can display the user's actual input
        // instead of the vision-enhanced text.
        if let Some(imgs) = image_contexts.as_ref().filter(|imgs| !imgs.is_empty()) {
            let image_meta: Vec<serde_json::Value> = imgs
                .iter()
                .map(|img| {
                    let name = img
                        .metadata
                        .as_ref()
                        .and_then(|m| m.get("name"))
                        .and_then(|v| v.as_str())
                        .unwrap_or("image.png");
                    let mut meta = serde_json::json!({
                        "id": &img.id,
                        "name": name,
                        "mime_type": &img.mime_type,
                    });
                    if let Some(url) = &img.data_url {
                        meta["data_url"] = serde_json::json!(url);
                    }
                    if let Some(path) = &img.image_path {
                        meta["image_path"] = serde_json::json!(path);
                    }
                    meta
                })
                .collect();

            let mut metadata =
                Self::ensure_user_message_metadata_object(user_message_metadata.take());
            if let Some(obj) = metadata.as_object_mut() {
                obj.insert("images".to_string(), serde_json::json!(image_meta));
                obj.insert(
                    "original_text".to_string(),
                    serde_json::json!(original_user_input.clone()),
                );
            }
            user_message_metadata = Some(metadata);
        }

        // Auto vision pre-analysis: when images are present, try to use the configured
        // vision model to pre-analyze them, then enhance the user message with text descriptions.
        // This is the single authoritative code path for all image handling (desktop, remote, bot).
        // If no vision model is configured, the request is rejected with a user-friendly message.
        let session_workspace = Self::session_workspace_binding(&session);
        let (user_input, image_contexts) = self
            .pre_analyze_images_if_needed(
                user_input,
                image_contexts,
                &session_id,
                user_message_metadata.clone(),
                session_workspace.clone(),
            )
            .await?;

        let wrapped_user_input = self
            .wrap_user_input(
                &effective_agent_type,
                user_input,
                session_workspace.as_ref(),
            )
            .await?;

        if original_user_input != wrapped_user_input {
            let mut metadata =
                Self::ensure_user_message_metadata_object(user_message_metadata.take());
            if let Some(obj) = metadata.as_object_mut() {
                obj.insert(
                    "original_text".to_string(),
                    serde_json::json!(original_user_input.clone()),
                );
            }
            user_message_metadata = Some(metadata);
        }

        // Start new dialog turn (sets state to Processing internally)
        let turn_index = self.session_manager.get_turn_count(&session_id);
        // Pass frontend turnId, generate if not provided
        let turn_id = self
            .session_manager
            .start_dialog_turn(
                &session_id,
                wrapped_user_input.clone(),
                turn_id,
                image_contexts,
                user_message_metadata.clone(),
            )
            .await?;

        // Send dialog turn started event with original input and image metadata
        // so all frontends (desktop, mobile, bot) can display correctly.
        self.emit_event(AgenticEvent::DialogTurnStarted {
            session_id: session_id.clone(),
            turn_id: turn_id.clone(),
            turn_index,
            user_input: wrapped_user_input.clone(),
            original_user_input: if original_user_input != wrapped_user_input {
                Some(original_user_input.clone())
            } else {
                None
            },
            user_message_metadata: user_message_metadata.clone(),
            subagent_parent_info: None,
        })
        .await;

        // Get context messages (re-fetch as history may have been restored)
        let messages = self
            .session_manager
            .get_context_messages(&session_id)
            .await?;

        // Create execution context (pass full config and resource IDs)
        let mut context_vars = std::collections::HashMap::new();
        context_vars.insert(
            "max_context_tokens".to_string(),
            session.config.max_context_tokens.to_string(),
        );
        context_vars.insert(
            "enable_tools".to_string(),
            session.config.enable_tools.to_string(),
        );
        context_vars.insert(
            "original_user_input".to_string(),
            original_user_input.clone(),
        );

        // Pass model_id for token usage tracking
        if let Some(model_id) = &session.config.model_id {
            context_vars.insert("model_name".to_string(), model_id.clone());
        }

        // Pass snapshot session ID
        if let Some(snapshot_id) = &session.snapshot_session_id {
            context_vars.insert("snapshot_session_id".to_string(), snapshot_id.clone());
        }

        // Pass turn_index (for operation history/rollback)
        context_vars.insert("turn_index".to_string(), turn_index.to_string());
        let session_workspace_path = session_workspace
            .as_ref()
            .map(|workspace| workspace.root_path_string());

        let execution_context = ExecutionContext {
            session_id: session_id.clone(),
            dialog_turn_id: turn_id.clone(),
            turn_index,
            agent_type: effective_agent_type.clone(),
            workspace: session_workspace,
            context: context_vars,
            subagent_parent_info: None,
            skip_tool_confirmation: submission_policy.skip_tool_confirmation,
        };

        // Auto-generate session title on first message
        if turn_index == 0 && !suppress_session_title_generation {
            let sm = self.session_manager.clone();
            let eq = self.event_queue.clone();
            let sid = session_id.clone();
            let msg = original_user_input;
            tokio::spawn(async move {
                let enabled = match crate::service::config::get_global_config_service().await {
                    Ok(svc) => svc
                        .get_config::<bool>(Some(
                            "app.ai_experience.enable_session_title_generation",
                        ))
                        .await
                        .unwrap_or(true),
                    Err(_) => true,
                };
                if !enabled {
                    return;
                }
                match sm.generate_session_title(&msg, Some(20)).await {
                    Ok(title) => {
                        if let Err(e) = sm.update_session_title(&sid, &title).await {
                            debug!("Failed to persist auto-generated title: {e}");
                        }
                        let _ = eq
                            .enqueue(
                                AgenticEvent::SessionTitleGenerated {
                                    session_id: sid,
                                    title,
                                    method: "ai".to_string(),
                                },
                                Some(EventPriority::Normal),
                            )
                            .await;
                    }
                    Err(e) => {
                        debug!("Auto session title generation failed: {e}");
                    }
                }
            });
        }

        // Start async execution task
        let session_manager = self.session_manager.clone();
        let execution_engine = self.execution_engine.clone();
        let event_queue = self.event_queue.clone();
        let session_id_clone = session_id.clone();
        let turn_id_clone = turn_id.clone();
        let user_input_for_workspace = wrapped_user_input.clone();
        let effective_agent_type_clone = effective_agent_type.clone();
        let user_message_metadata_clone = user_message_metadata;
        let scheduler_notify_tx = self.scheduler_notify_tx.get().cloned();

        tokio::spawn(async move {
            // Note: Don't check cancellation here as cancel token hasn't been created yet
            // Cancel token is created in execute_dialog_turn -> execute_round
            // execute_dialog_turn has proper cancellation checks internally

            let _ = session_manager
                .update_session_state(
                    &session_id_clone,
                    SessionState::Processing {
                        current_turn_id: turn_id_clone.clone(),
                        phase: ProcessingPhase::Thinking,
                    },
                )
                .await;

            let workspace_turn_status = match execution_engine
                .execute_dialog_turn(effective_agent_type_clone, messages, execution_context)
                .await
            {
                Ok(execution_result) => {
                    let final_response = match &execution_result.final_message.content {
                        MessageContent::Text(text) => text.clone(),
                        MessageContent::Mixed { text, .. } => text.clone(),
                        _ => String::new(),
                    };
                    info!(
                        "Dialog turn completed: session={}, turn={}, rounds={}",
                        session_id_clone, turn_id_clone, execution_result.total_rounds
                    );

                    let _ = session_manager
                        .complete_dialog_turn(
                            &session_id_clone,
                            &turn_id_clone,
                            final_response.clone(),
                            TurnStats {
                                total_rounds: execution_result.total_rounds,
                                total_tools: 0, // TODO: get from execution_result
                                total_tokens: 0,
                                duration_ms: 0,
                            },
                        )
                        .await;

                    let _ = session_manager
                        .update_session_state(&session_id_clone, SessionState::Idle)
                        .await;

                    if let Some(tx) = &scheduler_notify_tx {
                        let _ = tx.try_send((
                            session_id_clone.clone(),
                            TurnOutcome::Completed {
                                turn_id: turn_id_clone.clone(),
                                final_response,
                            },
                        ));
                    }

                    Some(crate::service::session::TurnStatus::Completed)
                }
                Err(e) => {
                    let is_cancellation = matches!(&e, BitFunError::Cancelled(_));

                    if is_cancellation {
                        info!(
                            "Dialog turn cancelled: session={}, turn={}",
                            session_id_clone, turn_id_clone
                        );

                        // The execution engine only emits DialogTurnCancelled when
                        // cancellation is detected between rounds.  If cancellation
                        // interrupted streaming mid-round, no event was emitted.
                        // Emit it here unconditionally (duplicates are harmless).
                        let _ = event_queue
                            .enqueue(
                                AgenticEvent::DialogTurnCancelled {
                                    session_id: session_id_clone.clone(),
                                    turn_id: turn_id_clone.clone(),
                                    subagent_parent_info: None,
                                },
                                Some(EventPriority::Critical),
                            )
                            .await;

                        // Mark the turn as completed in persistence so its partial
                        // content appears in historical messages (turns_to_chat_messages
                        // skips InProgress turns).
                        let _ = session_manager
                            .complete_dialog_turn(
                                &session_id_clone,
                                &turn_id_clone,
                                String::new(),
                                TurnStats {
                                    total_rounds: 0,
                                    total_tools: 0,
                                    total_tokens: 0,
                                    duration_ms: 0,
                                },
                            )
                            .await;

                        let _ = session_manager
                            .update_session_state(&session_id_clone, SessionState::Idle)
                            .await;

                        if let Some(tx) = &scheduler_notify_tx {
                            let _ = tx.try_send((
                                session_id_clone.clone(),
                                TurnOutcome::Cancelled {
                                    turn_id: turn_id_clone.clone(),
                                },
                            ));
                        }

                        Some(crate::service::session::TurnStatus::Cancelled)
                    } else {
                        let error_text = e.to_string();
                        error!("Dialog turn execution failed: {}", error_text);

                        let recoverable =
                            !matches!(&e, BitFunError::AIClient(_) | BitFunError::Timeout(_));

                        let _ = event_queue
                            .enqueue(
                                AgenticEvent::DialogTurnFailed {
                                    session_id: session_id_clone.clone(),
                                    turn_id: turn_id_clone.clone(),
                                    error: error_text.clone(),
                                    subagent_parent_info: None,
                                },
                                Some(EventPriority::Critical),
                            )
                            .await;

                        let _ = session_manager
                            .fail_dialog_turn(&session_id_clone, &turn_id_clone, error_text.clone())
                            .await;

                        let _ = session_manager
                            .update_session_state(
                                &session_id_clone,
                                SessionState::Error {
                                    error: error_text.clone(),
                                    recoverable,
                                },
                            )
                            .await;

                        if let Some(tx) = &scheduler_notify_tx {
                            let _ = tx.try_send((
                                session_id_clone.clone(),
                                TurnOutcome::Failed {
                                    turn_id: turn_id_clone.clone(),
                                    error: error_text,
                                },
                            ));
                        }

                        Some(crate::service::session::TurnStatus::Error)
                    }
                }
            };

            if let (Some(ref wp), Some(status)) = (&session_workspace_path, workspace_turn_status) {
                Self::finalize_turn_in_workspace(
                    &session_id_clone,
                    &turn_id_clone,
                    turn_index,
                    &user_input_for_workspace,
                    wp,
                    status,
                    user_message_metadata_clone,
                )
                .await;
            }
        });

        Ok(())
    }

    /// Cancel dialog turn execution
    /// Immediately set state to Idle to allow new dialog, old turn ends naturally via cancel token
    pub async fn cancel_dialog_turn(
        &self,
        session_id: &str,
        dialog_turn_id: &str,
    ) -> BitFunResult<()> {
        info!(
            "Received cancel request: dialog_turn_id={}, session_id={}",
            dialog_turn_id, session_id
        );

        let old_state = self
            .session_manager
            .get_session(session_id)
            .map(|s| format!("{:?}", s.state))
            .unwrap_or_else(|| "Unknown".to_string());
        debug!("Current state: {}", old_state);

        // Step 1: Immediately update session state to Idle (non-blocking, allows immediate new dialog)
        debug!("Updating session state to Idle");
        self.session_manager
            .update_session_state(session_id, SessionState::Idle)
            .await?;

        let new_state = self
            .session_manager
            .get_session(session_id)
            .map(|s| format!("{:?}", s.state))
            .unwrap_or_else(|| "Unknown".to_string());
        debug!("State updated: {} -> {}", old_state, new_state);

        // Step 2: Immediately send state change event (notify frontend can start new dialog)
        self.emit_event(AgenticEvent::SessionStateChanged {
            session_id: session_id.to_string(),
            new_state: "idle".to_string(),
        })
        .await;
        debug!("Session state change event sent");

        // Step 3: Async cleanup of old turn (let it end naturally via cancel token, non-blocking)
        let execution_engine = self.execution_engine.clone();
        let tool_pipeline = self.tool_pipeline.clone();
        let dialog_turn_id_clone = dialog_turn_id.to_string();

        tokio::spawn(async move {
            debug!(
                "Starting async cleanup for cancelled turn: {}",
                dialog_turn_id_clone
            );

            if let Err(e) = execution_engine
                .cancel_dialog_turn(&dialog_turn_id_clone)
                .await
            {
                warn!("Failed to cancel execution engine: {}", e);
            }

            if let Err(e) = tool_pipeline
                .cancel_dialog_turn_tools(&dialog_turn_id_clone)
                .await
            {
                warn!("Failed to cancel tool execution: {}", e);
            }

            debug!("Async cleanup completed: {}", dialog_turn_id_clone);
        });

        Ok(())
    }

    /// Delete session
    pub async fn delete_session(
        &self,
        workspace_path: &Path,
        session_id: &str,
    ) -> BitFunResult<()> {
        self.session_manager
            .delete_session(workspace_path, session_id)
            .await?;
        self.emit_event(AgenticEvent::SessionDeleted {
            session_id: session_id.to_string(),
        })
        .await;
        Ok(())
    }

    /// Restore session
    pub async fn restore_session(
        &self,
        workspace_path: &Path,
        session_id: &str,
    ) -> BitFunResult<Session> {
        self.session_manager
            .restore_session(workspace_path, session_id)
            .await
    }

    /// List all sessions
    pub async fn list_sessions(&self, workspace_path: &Path) -> BitFunResult<Vec<SessionSummary>> {
        self.session_manager.list_sessions(workspace_path).await
    }

    /// Get session messages
    pub async fn get_messages(&self, session_id: &str) -> BitFunResult<Vec<Message>> {
        self.session_manager.get_messages(session_id).await
    }

    /// Get session messages paginated
    pub async fn get_messages_paginated(
        &self,
        session_id: &str,
        limit: usize,
        before_message_id: Option<&str>,
    ) -> BitFunResult<(Vec<Message>, bool)> {
        self.session_manager
            .get_messages_paginated(session_id, limit, before_message_id)
            .await
    }

    /// Subscribe to internal events
    ///
    /// For internal systems to subscribe to events (e.g., logging, monitoring)
    pub fn subscribe_internal<H>(&self, subscriber_id: String, handler: H)
    where
        H: EventSubscriber + 'static,
    {
        self.event_router
            .subscribe_internal(subscriber_id, Arc::new(handler));
    }

    /// Unsubscribe from internal events
    ///
    /// Remove subscriber previously added via subscribe_internal
    pub fn unsubscribe_internal(&self, subscriber_id: &str) {
        self.event_router.unsubscribe_internal(subscriber_id);
    }

    /// Confirm tool execution
    pub async fn confirm_tool(
        &self,
        tool_id: &str,
        updated_input: Option<serde_json::Value>,
    ) -> BitFunResult<()> {
        self.tool_pipeline
            .confirm_tool(tool_id, updated_input)
            .await
    }

    /// Reject tool execution
    pub async fn reject_tool(&self, tool_id: &str, reason: String) -> BitFunResult<()> {
        self.tool_pipeline.reject_tool(tool_id, reason).await
    }

    /// Cancel tool execution
    pub async fn cancel_tool(&self, tool_id: &str, reason: String) -> BitFunResult<()> {
        self.tool_pipeline.cancel_tool(tool_id, reason).await
    }

    /// Execute subagent task directly
    /// DialogTurnStarted event not needed for now
    ///
    /// Parameters:
    /// - agent_type: Agent type
    /// - task_description: Task description
    /// - subagent_parent_info: Parent info (tool call context)
    /// - context: Additional context
    /// - cancel_token: Optional cancel token (for async cancellation)
    ///
    /// Returns SubagentResult with the final text response
    pub async fn execute_subagent(
        &self,
        agent_type: String,
        task_description: String,
        subagent_parent_info: SubagentParentInfo,
        workspace_path: Option<String>,
        context: Option<std::collections::HashMap<String, String>>,
        cancel_token: Option<&CancellationToken>,
    ) -> BitFunResult<SubagentResult> {
        // Check cancel token (before creating session)
        if let Some(token) = cancel_token {
            if token.is_cancelled() {
                debug!("Subagent task cancelled before execution");
                return Err(BitFunError::Cancelled(
                    "Subagent task has been cancelled".to_string(),
                ));
            }
        }

        // Create independent subagent session.
        // Use create_subagent_session (not create_session) so that no SessionCreated
        // event is emitted to the transport layer — subagent sessions are internal
        // implementation details and must not appear in the UI session list.
        let workspace_path = workspace_path.ok_or_else(|| {
            BitFunError::Validation(
                "workspace_path is required when creating a subagent session".to_string(),
            )
        })?;
        let mut subagent_config = SessionConfig::default();
        subagent_config.workspace_path = Some(workspace_path);
        let session = self
            .create_subagent_session(
                format!("Subagent: {}", task_description),
                agent_type.clone(),
                subagent_config,
                Some(&subagent_parent_info.session_id),
            )
            .await?;

        // Check cancel token (after creating session, before execution)
        if let Some(token) = cancel_token {
            if token.is_cancelled() {
                debug!("Subagent task cancelled before AI call, cleaning up resources");
                let _ = self.cleanup_subagent_resources(&session.session_id).await;
                return Err(BitFunError::Cancelled(
                    "Subagent task has been cancelled".to_string(),
                ));
            }
        }

        // Generate unique dialog_turn_id for cancel token management
        let dialog_turn_id = format!("subagent-{}", uuid::Uuid::new_v4());
        debug!(
            "Generated unique dialog_turn_id for subagent: {}",
            dialog_turn_id
        );

        // If external cancel_token provided, create child_token and register to RoundExecutor
        // This allows execute_dialog_turn internal checks to detect external cancellation
        let _cleanup_guard = if let Some(parent_token) = cancel_token {
            // Create child_token, cancelled when parent_token is cancelled
            let child_token = parent_token.child_token();

            // Register to ExecutionEngine (forwarded to RoundExecutor), using dialog_turn_id as key
            self.execution_engine
                .register_cancel_token(&dialog_turn_id, child_token.clone());

            debug!(
                "Registered cancel token to RoundExecutor: dialog_turn_id={}",
                dialog_turn_id
            );

            // Create cleanup guard to ensure token cleanup on function exit
            Some(CancelTokenGuard {
                execution_engine: self.execution_engine.clone(),
                dialog_turn_id: dialog_turn_id.clone(),
            })
        } else {
            None
        };

        let execution_context = ExecutionContext {
            session_id: session.session_id.clone(),
            dialog_turn_id: dialog_turn_id.clone(),
            turn_index: 0,
            agent_type: agent_type.clone(),
            workspace: Self::session_workspace_binding(&session),
            context: context.unwrap_or_default(),
            subagent_parent_info: Some(subagent_parent_info),
            skip_tool_confirmation: false,
        };

        let initial_messages = vec![Message::user(task_description)];

        let result = self
            .execution_engine
            .execute_dialog_turn(agent_type, initial_messages, execution_context)
            .await;

        // cleanup_guard automatically cleans up token on scope exit (via Drop trait)

        // Extract text response
        let response_text = match result {
            Ok(exec_result) => match exec_result.final_message.content {
                MessageContent::Mixed { text, .. } => text,
                MessageContent::Text(text) => text,
                _ => String::new(),
            },
            Err(e) => {
                error!(
                    "Subagent execution failed: session={}, error={}",
                    session.session_id, e
                );

                if let Err(cleanup_err) = self.cleanup_subagent_resources(&session.session_id).await
                {
                    warn!(
                        "Failed to cleanup subagent resources: session={}, error={}",
                        session.session_id, cleanup_err
                    );
                }

                return Err(e);
            }
        };

        // Clean up subagent session resources after successful execution
        debug!(
            "Starting subagent resource cleanup: session={}",
            session.session_id
        );
        if let Err(e) = self.cleanup_subagent_resources(&session.session_id).await {
            warn!(
                "Failed to cleanup subagent resources: session={}, error={}",
                session.session_id, e
            );
        } else {
            debug!(
                "Subagent resource cleanup completed: session={}",
                session.session_id
            );
        }

        Ok(SubagentResult {
            text: response_text,
        })
    }

    /// Clean up subagent session resources
    ///
    /// Release resources occupied by subagent session (sandbox, etc.) and delete session
    async fn cleanup_subagent_resources(&self, session_id: &str) -> BitFunResult<()> {
        debug!(
            "Starting subagent resource cleanup: session_id={}",
            session_id
        );

        // Clean up snapshot system resources
        if let Some(workspace_path) = self
            .session_manager
            .get_session(session_id)
            .and_then(|session| session.config.workspace_path.map(std::path::PathBuf::from))
        {
            if let Ok(snapshot_manager) =
                crate::service::snapshot::ensure_snapshot_manager_for_workspace(&workspace_path)
            {
                let snapshot_service = snapshot_manager.get_snapshot_service();
                let snapshot_service = snapshot_service.read().await;
                if let Err(e) = snapshot_service.accept_session(session_id).await {
                    warn!(
                        "Failed to cleanup snapshot system resources: session={}, error={}",
                        session_id, e
                    );
                } else {
                    debug!(
                        "Snapshot system resources cleaned up: session={}",
                        session_id
                    );
                }
            }
        }

        // Delete subagent session itself (including message history, persistence data, etc.)
        let workspace_path = self
            .session_manager
            .get_session(session_id)
            .and_then(|session| session.config.workspace_path.map(std::path::PathBuf::from));

        if let Some(workspace_path) = workspace_path {
            if let Err(e) = self
                .session_manager
                .delete_session(&workspace_path, session_id)
                .await
            {
                warn!(
                    "Failed to delete subagent session: session={}, error={}",
                    session_id, e
                );
            } else {
                debug!("Subagent session deleted: session={}", session_id);
            }
        } else {
            warn!(
                "Failed to delete subagent session because workspace_path is missing: session={}",
                session_id
            );
        }

        debug!(
            "Subagent resource cleanup completed: session_id={}",
            session_id
        );
        Ok(())
    }

    /// Generate session title
    ///
    /// Use AI to generate a concise and accurate session title based on user message content.
    /// Also persists the title to the session backend. Callers that go through
    /// `start_dialog_turn` do NOT need to call this separately — first-message
    /// title generation is handled automatically inside `start_dialog_turn`.
    pub async fn generate_session_title(
        &self,
        session_id: &str,
        user_message: &str,
        max_length: Option<usize>,
    ) -> BitFunResult<String> {
        let title = self
            .session_manager
            .generate_session_title(user_message, max_length)
            .await?;

        if let Err(e) = self
            .session_manager
            .update_session_title(session_id, &title)
            .await
        {
            debug!("Failed to persist generated title: {e}");
        }

        let event = AgenticEvent::SessionTitleGenerated {
            session_id: session_id.to_string(),
            title: title.clone(),
            method: "ai".to_string(),
        };
        self.emit_event(event).await;

        debug!(
            "Session title generation event sent: session_id={}, title={}",
            session_id, title
        );

        Ok(title)
    }

    /// Emit event
    async fn emit_event(&self, event: AgenticEvent) {
        let _ = self
            .event_queue
            .enqueue(event, Some(EventPriority::Normal))
            .await;
    }

    /// Get SessionManager reference (for advanced features like mode management)
    pub fn get_session_manager(&self) -> &Arc<SessionManager> {
        &self.session_manager
    }

    /// Set global coordinator (called during initialization)
    ///
    /// Skips if global coordinator already exists
    pub fn set_global(coordinator: Arc<ConversationCoordinator>) {
        match GLOBAL_COORDINATOR.set(coordinator) {
            Ok(_) => {
                debug!("Global coordinator set");
            }
            Err(_) => {
                debug!("Global coordinator already exists, skipping set");
            }
        }
    }
}

// Global coordinator singleton
static GLOBAL_COORDINATOR: OnceLock<Arc<ConversationCoordinator>> = OnceLock::new();

/// Get global coordinator
///
/// Returns `None` if coordinator hasn't been initialized
pub fn get_global_coordinator() -> Option<Arc<ConversationCoordinator>> {
    GLOBAL_COORDINATOR.get().cloned()
}
